local attributes = {
  "stroke-width",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-dasharray",
  "stroke-dashoffset",
  "fill-opacity",
  "stroke-opacity",
  "stop-opacity",
  "color-interpolation",
  "color-rendering",
  "shape-rendering",
  "text-rendering",
  "view-box",
  "gradient-units",
  "pattern-units",
  "pattern-content-units",
  "preserve-aspect-ratio",
  "clip-path",
  "clip-rule",
  "mask-type",
  "filter-units",
  "flood-color",
  "flood-opacity",
  "lighting-color",
  "attribute-name",
  "attribute-type",
  "repeat-count",
  "key-splines",
  "key-times"
}

return attributes
